// Periodic boundary conditions
#[macro_export]
macro_rules! Heisenberg5X5 {
  ($x:ty, $tau:expr) => {
    [
        QInstruction::Q2 { idx1: 0, idx2: 5, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 1, idx2: 6, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 2, idx2: 7, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 3, idx2: 8, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 4, idx2: 9, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 10, idx2: 15, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 11, idx2: 16, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 12, idx2: 17, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 13, idx2: 18, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 14, idx2: 19, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 5, idx2: 10, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 6, idx2: 11, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 7, idx2: 12, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 8, idx2: 13, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 9, idx2: 14, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 15, idx2: 20, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 16, idx2: 21, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 17, idx2: 22, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 18, idx2: 23, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 19, idx2: 24, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 0, idx2: 1, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 5, idx2: 6, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 10, idx2: 11, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 15, idx2: 16, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 20, idx2: 21, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 2, idx2: 3, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 7, idx2: 8, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 12, idx2: 13, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 17, idx2: 18, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 22, idx2: 23, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 1, idx2: 2, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 6, idx2: 7, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 11, idx2: 12, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 16, idx2: 17, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 21, idx2: 22, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 3, idx2: 4, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 8, idx2: 9, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 13, idx2: 14, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 18, idx2: 19, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 23, idx2: 24, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 0, idx2: 4, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 5, idx2: 9, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 10, idx2: 14, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 15, idx2: 19, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 20, idx2: 24, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 0, idx2: 20, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 1, idx2: 21, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 2, idx2: 22, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 3, idx2: 23, gate: Heisenberg!($x, $tau) },
        QInstruction::Q2 { idx1: 4, idx2: 24, gate: Heisenberg!($x, $tau) },
    ]
  }
}